# Generated by Django 5.1.1 on 2024-09-06 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0001_initial'),
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('bills', models.ManyToManyField(to='bill.bill')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.investor')),
            ],
        ),
    ]
