# Generated by Django 5.1.1 on 2024-09-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalcall',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'validated'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], max_length=20),
        ),
    ]
