# Generated by Django 5.1.1 on 2024-09-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('iban', models.CharField(max_length=34)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_date', models.DateField()),
            ],
        ),
    ]
