# Generated by Django 5.1.1 on 2024-09-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_alter_investor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='investment_amount',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='investment_date',
        ),
    ]
