# Generated by Django 5.1.1 on 2024-09-07 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
        ('investor', '0002_alter_investor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='investor.investor'),
        ),
    ]
