# Generated by Django 5.1.1 on 2024-09-08 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_alter_bill_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='investment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
